### ISSUE TITLE
The phenopacket examples are not valid phenopackets

### ISSUE THREAD

**Issue by cmungall** [GA4GH-Pedigree-Standard/pedigree#37]
I'm looking at the documentation to see if I can understand whether the proposed Conceptual Model is equivalent to or more expressive than the Phenopackets [Pedigree element](https://phenopacket-schema.readthedocs.io/en/latest/pedigree.html).

The examples page here https://pedigree.readthedocs.io/en/latest/examples.html is potentially useful here, but I'm confused by it. It says

"As a Phenopacket GA4GHPedigree message:"

and then gives:

```yaml
id: FAM1
narrative: A Phenopacket GA4GHPedigree of a trio with an affected child
date: 2022-06-23
individuals:
  - id: 1
    subject:
      id: MOTHER
      sex: FEMALE
  - id: 2
    subject:
      id: FATHER
      sex: MALE
  - id: 3
    subject:
      id: CHILD
      sex: UNKNOWN
relationships:
  - individual_id: MOTHER
    relation:
      id: KIN:027
      label: isBiologicalMotherOf
    relative_id: CHILD
  - individual_id: FATHER
    relation:
      id: KIN:028
      label: isBiologicalFatherOf
    relative_id: CHILD
index_patients:
  - CHILD
```

But this doesn't seem to be conformant with the phenopacket spec

It looks more like a variant of the CM [here](https://pedigree.readthedocs.io/en/latest/pedigree-model.html) (but differs in the cardinality of `individual_id`).

I think it would be very useful to look at examples of the same familiar relationships in different data models side by side, but I'm not totally sure what I am looking at here
